### ISSUE TITLE
TypeError exception: can't define singleton

### ISSUE THREAD

**Issue by ritaritual** [edporras/edn_turbo#4]
I just tried parse some EDN (routes for bidi) with some meta, and got this:
```ruby
[margo] pry
[1] pry(main)> require 'edn_turbo'
=> true
[2] pry(main)> EDN.read('["/" {"index.html" :index "articles/" {"index.html" ^:list :article-index "article.html" :article}}]')
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: TypeError exception: can't define singleton
[1]    99990 abort      pry
[margo] pry
[1] pry(main)> require 'edn_turbo'
=> true
[2] pry(main)> EDN.read('["/" {"index.html" :index "articles/" {"index.html" ^{:list true} :article-index "article.html" :article}}]')
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: TypeError exception: can't define singleton
[1]    189 abort      pry
```

**Comment by edporras** [comment]
Hi Rita,

I've tested on Ubuntu and macOS with ruby 2.2.x, 2.3.x, and the latest I did was 2.4.1 without problems. What OS & ruby version are you using? 

Thanks.

**Comment by ritaritual** [comment]
Hi Ed,

I found that keywords ( at least in Clojure ) do not support metadata... not sure about EDN... 

OS X Sierra version 10.13.2 (17C88)
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

Thank YOU for this awesome gem 💎 😸 

I'm not sure... but maybe there also needed some exception like...
```clojure
user=> (read-string ":edporras")
:edporras
user=> (read-string "^:awesome :edporras")

IllegalArgumentException Metadata can only be applied to IMetas  clojure.lang.LispReader$MetaReader.invoke (LispReader.java:820)
user=>
```

**Comment by ritaritual** [comment]
Hmmm... Ed, sorry... it's all about `edn` gem... not about `edn_turbo`
```
[1] pry(main)> require "edn"
=> true
[2] pry(main)> EDN.read('["/" {"index.html" :index "articles/" {"index.html" ^:list :article-index "article.html" :article}}]')
TypeError: can't define singleton
from /Users/margo/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/edn-1.1.1/lib/edn/ruby_edn_parser.rb:16:in `extend_object'
```

**Comment by edporras** [comment]
Haha. No problem at all. Happy new year. 😀

**Comment by ritaritual** [comment]
@edporras thank you! you too! )))
But... in the end I think there is still a small problem...
I think in my case `edn_turbo` do not handle Exception correctly... If in `edn` gem it's just Exception, `edn_turbo` crashes at all on this exception. I meant Ruby process halts on this.

**Comment by edporras** [comment]
Ok, I'll give it a try asap and let you know. Thanks.

**Comment by edporras** [comment]
I've pushed v0.5.4 to ruby gems. It'd been a while since I last looked at the code but I realized I was throwing a C++ exception instead of raising a ruby error when certain issues happened. I've changed it to use `rb_raise` instead. Can you test it and let me know if you see anything odd?

**Comment by ritaritual** [comment]
I'm sorry for so long silence

```ruby
[margo] gem update edn_turbo                                                                                                                        master
Updating installed gems
Updating edn_turbo
Fetching: edn_turbo-0.5.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed edn_turbo-0.5.5
Parsing documentation for edn_turbo-0.5.5
Installing ri documentation for edn_turbo-0.5.5
Installing darkfish documentation for edn_turbo-0.5.5
(eval):9: warning: regex literal in condition
Done installing documentation for edn_turbo after 1 seconds
Parsing documentation for edn_turbo-0.5.5
Done installing documentation for edn_turbo after 0 seconds
Gems updated: edn_turbo
[margo] pry                                                                                                                                         master
[1] pry(main)> require 'edn_turbo'
=> true
[2] pry(main)> EDN.read('["/" {"index.html" :index "articles/" {"index.html" ^:list :article-index "article.html" :article}}]')
TypeError: can't define singleton
from /Users/grach/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/edn-1.1.1/lib/edn/reader.rb:9:in `read'
```
@edporras you are awesome! 💋 
Now it's handle exception correct!!! )))

**Comment by edporras** [comment]
👍 😄
